# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/shudianzuoye/CPU9_8/CPU9_8.srcs/sources_1/ip/RAM_C/RAM_C.xci
# IP: The module: 'RAM_C' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/shudianzuoye/CPU9_8/CPU9_8.srcs/sources_1/ip/RAM_C/RAM_C_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_C'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/shudianzuoye/CPU9_8/CPU9_8.srcs/sources_1/ip/RAM_C/RAM_C.xci
# IP: The module: 'RAM_C' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/shudianzuoye/CPU9_8/CPU9_8.srcs/sources_1/ip/RAM_C/RAM_C_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_C'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
